#Requires -Version 5.1
<#
.SYNOPSIS
    Registers this laptop in Snipe-IT under the fixed model "VUT laptop".

.DESCRIPTION
    - Collects hardware data via CIM: serial, real make/model, CPU, RAM, storage, OS, battery.
    - Checks Snipe-IT by serial; if the asset exists -> returns its asset tag, exit 2.
    - Resolves the Snipe-IT model and status label by name (read-only, never created).
    - Creates the asset; asset tag is generated by Snipe-IT (auto-increment must be enabled).
    - Custom fields are free text (format ANY); real make/model goes to "Laptop model".
    - Stamps the asset tag (created or existing) onto the desktop wallpaper:
        admin  -> device-wide via PersonalizationCSP (all users, locks wallpaper)
        user   -> current user via SystemParametersInfo
      Wallpaper failure never fails registration; see "wallpaper" in the JSON output.
      -DryRun only renders a preview image to %TEMP%.
    - Audit trail: the asset "notes" record script version, time, Windows account and hostname;
      every JSON result line (incl. -DryRun and errors) is appended to
      C:\ProgramData\SnipeIT\register.log (failure to log never changes the result).

    Output: one JSON line on stdout, e.g.
      {"result":"created","asset_tag":"VUT00123","id":45,...}
      {"result":"exists","asset_tag":"VUT00077","id":12,...}
      {"result":"error","message":"..."}

    Exit codes: 0 = created, 2 = already registered, 1 = error.

.EXAMPLE
    # Token: put it into snipeit.token next to the script (git-ignored), or $env:SNIPEIT_TOKEN
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File .\Register-SnipeAsset.ps1 -DryRun
    powershell.exe -NoProfile -ExecutionPolicy Bypass -File .\Register-SnipeAsset.ps1
#>
[CmdletBinding()]
param(
    [string]$SnipeUrl     = 'https://inventorius.liepu27.lt',
    [string]$ApiToken     = $env:SNIPEIT_TOKEN,   # fallback: snipeit.token next to the script

    [string]$StatusName   = 'Ready to Deploy',  # Existing Snipe-IT status label, resolved by name
    [int]$StatusId        = 0,             # Set to skip the name lookup
    [string]$ModelName    = 'VUT laptop',  # Existing Snipe-IT model, resolved by name
    [int]$ModelId         = 0,             # Set to skip the name lookup

    # DB column names of custom fields (Settings -> Custom Fields -> "DB Field")
    [string]$FieldLaptopModel = '_snipeit_laptop_model_8',
    [string]$FieldCpu         = '_snipeit_cpu_2',
    [string]$FieldRam         = '_snipeit_ram_3',
    [string]$FieldStorageGb   = '_snipeit_storage_gb_4',
    [string]$FieldStorageType = '_snipeit_storage_type_5',
    [string]$FieldOs          = '_snipeit_operating_system_6',
    [string]$FieldBattery     = '_snipeit_batery_health_7',

    [string]$Serial,       # Override BIOS serial for testing; only allowed together with -DryRun

    # Wallpaper stamping
    [string]$WallpaperBase = "$env:windir\Web\Wallpaper\Windows\img0.jpg",  # background; solid colour if missing
    [string]$WallpaperPath = "$env:ProgramData\SnipeIT\wallpaper.png",      # must be readable by all users
    [switch]$NoWallpaper,

    [switch]$DryRun        # collect + read-only checks, no writes
)

$ErrorActionPreference = 'Stop'
# Add TLS 1.2 without disabling protocols that are already enabled. SystemDefault (0) lets the OS
# choose (TLS 1.2/1.3 on Win10/11) - leave it alone: 0 -bor Tls12 would pin TLS 1.2 only.
$tlsNow = [Net.ServicePointManager]::SecurityProtocol
if ([int]$tlsNow -ne 0) {
    [Net.ServicePointManager]::SecurityProtocol = $tlsNow -bor [Net.SecurityProtocolType]::Tls12
}

$ScriptVersion = '1.1.0'
$AuditLogPath  = "$env:ProgramData\SnipeIT\register.log"
$RunAs         = "$env:USERDOMAIN\$env:USERNAME"
try { $RunAs = [Security.Principal.WindowsIdentity]::GetCurrent().Name }   # e.g. NT AUTHORITY\SYSTEM under Intune
catch { Write-Verbose 'WindowsIdentity unavailable, using USERDOMAIN\USERNAME' }

function Out-Result {
    param([hashtable]$Data, [int]$ExitCode)
    $json = $Data | ConvertTo-Json -Compress
    # Audit trail (ISO 27001 A.5.9): append every result line. Must never change stdout or the exit code.
    # Only $json is logged - it never contains the API token.
    try {
        $logDir = Split-Path $AuditLogPath
        if (-not (Test-Path $logDir)) { New-Item -ItemType Directory -Path $logDir | Out-Null }
        $line = "{0}`tv{1}`t{2}`t{3}" -f (Get-Date).ToString('yyyy-MM-ddTHH:mm:sszzz'), $ScriptVersion, $RunAs, $json
        Add-Content -Path $AuditLogPath -Value $line -Encoding UTF8
    } catch {
        Write-Verbose "Audit log not written: $($_.Exception.Message)"
    }
    Write-Output $json
    exit $ExitCode
}

# Readable message for a failed HTTP call: status code + (shortened) response body
function Get-SnipeHttpError {
    param($ErrorRecord, [string]$Method, [string]$Path)
    $resp = $ErrorRecord.Exception.Response
    if (-not $resp) { return "Snipe-IT network error ($Method $Path): $($ErrorRecord.Exception.Message)" }

    # PS 5.1 already reads the body into ErrorDetails; the stream is then at its end -> rewind as fallback
    $respBody = "$($ErrorRecord.ErrorDetails.Message)"
    if (-not $respBody -and $resp -is [Net.HttpWebResponse]) {
        try {
            $stream = $resp.GetResponseStream()
            if ($stream.CanSeek) { $stream.Position = 0 }
            $respBody = (New-Object IO.StreamReader $stream).ReadToEnd()
        } catch {
            Write-Verbose "Response body not readable: $($_.Exception.Message)"
        }
    }
    # Cloudflare / proxy error pages are long HTML -> keep the JSON line short
    $respBody = ($respBody -replace '\s+', ' ').Trim()
    if ($respBody.Length -gt 300) { $respBody = $respBody.Substring(0, 300) + '...' }
    "Snipe-IT HTTP $([int]$resp.StatusCode) ($Method $Path): $respBody"
}

function Invoke-Snipe {
    param(
        [ValidateSet('GET', 'POST', 'PATCH')] [string]$Method,
        [string]$Path,
        $Body,
        [switch]$AllowError
    )
    $p = @{ Method = $Method; Uri = "$base$Path"; Headers = $headers; TimeoutSec = 30 }
    if ($null -ne $Body) {
        # Send UTF-8 bytes explicitly (PS 5.1 otherwise mangles non-ASCII)
        $p.Body        = [Text.Encoding]::UTF8.GetBytes(($Body | ConvertTo-Json -Depth 5 -Compress))
        $p.ContentType = 'application/json; charset=utf-8'
    }

    # Retry up to 3 attempts with backoff (2 s, 4 s; 429 honours Retry-After):
    #   GET        - network error, HTTP 429, HTTP 5xx
    #   POST/PATCH - HTTP 429 only: after a timeout/5xx the write may already have happened,
    #                a retry could create a duplicate asset
    # Never retried: other 4xx, status=error in a 200 body.
    # UNTESTED: 429/5xx retry path against the live API
    $maxAttempts = 3
    for ($attempt = 1; ; $attempt++) {
        try {
            $r = Invoke-RestMethod @p
            break
        } catch {
            $ex = $_.Exception
            if (-not ($ex -is [Net.WebException] -or $ex -is [Net.Http.HttpRequestException])) { throw }
            $code = 0
            if ($ex.Response) { $code = [int]$ex.Response.StatusCode }
            $canRetry = $code -eq 429 -or ($Method -eq 'GET' -and ($code -eq 0 -or $code -ge 500))
            if (-not $canRetry -or $attempt -ge $maxAttempts) {
                throw (Get-SnipeHttpError -ErrorRecord $_ -Method $Method -Path $Path)
            }
            $delay = [int][math]::Pow(2, $attempt)
            if ($code -eq 429) {
                $retryAfter = ''
                try { $retryAfter = "$($ex.Response.Headers['Retry-After'])" }   # PS 5.1 WebHeaderCollection
                catch { Write-Verbose 'Retry-After header not readable' }
                if ($retryAfter -match '^\d+$') { $delay = [math]::Min([int]$retryAfter, 60) }
            }
            Write-Verbose "Attempt $attempt failed (HTTP $code), retrying in $delay s"
            Start-Sleep -Seconds $delay
        }
    }
    # Snipe-IT returns HTTP 200 on logical errors -> check body
    if (-not $AllowError -and $r.status -eq 'error') {
        throw "Snipe-IT API error ($Method $Path): $($r.messages | ConvertTo-Json -Compress)"
    }
    $r
}

function Find-ByName {
    param([string]$Endpoint, [string]$Name)
    $q   = [uri]::EscapeDataString($Name)
    $res = Invoke-Snipe GET "/$Endpoint`?search=$q&limit=100"
    # API returns HTML-encoded names
    $res.rows | Where-Object { [Net.WebUtility]::HtmlDecode($_.name) -eq $Name } | Select-Object -First 1
}

# ---------- Pure helpers (no I/O; covered by tests\Register-SnipeAsset.Tests.ps1) ----------

# Placeholder values firmware ships instead of a real serial / SKU
function Test-JunkSerial {
    param([string]$Value)
    $Value -match '^(|0+|none|default string|to be filled by o\.e\.m\.|system serial number|not specified|n/?a|chassis serial number)$'
}

# Real make/model for the "Laptop model" field, e.g. "Lenovo ThinkPad T14 Gen 3 (21CBS0AB00)"
# Inputs: Win32_ComputerSystem Manufacturer/Model/SystemSKUNumber, Win32_ComputerSystemProduct Version
function Get-LaptopModelString {
    param([string]$Manufacturer, [string]$Model, [string]$Version, [string]$Sku)
    $mfgMap = @{
        'Dell Inc.'             = 'Dell'
        'Hewlett-Packard'       = 'HP'
        'HP'                    = 'HP'
        'LENOVO'                = 'Lenovo'
        'Microsoft Corporation' = 'Microsoft'
        'ASUSTeK COMPUTER INC.' = 'ASUS'
    }
    $mfgRaw = "$Manufacturer".Trim()
    $vendor = if ($mfgMap.ContainsKey($mfgRaw)) { $mfgMap[$mfgRaw] } else { $mfgRaw }

    # NB: hw* prefix - PS variables are case-insensitive, $modelName would overwrite -ModelName
    if ($vendor -eq 'Lenovo') {
        # Lenovo: Model = machine type (e.g. 21CBS0AB00), Version = friendly name
        $hwModelName   = "$Version".Trim()
        $hwModelNumber = "$Model".Trim()
    } else {
        $hwModelName   = "$Model".Trim()
        $hwModelNumber = "$Sku".Trim()
    }
    # HP / Dell already prefix the model with the vendor ("HP EliteBook ...") -> don't duplicate
    $text = if ($hwModelName -like "$vendor *") { $hwModelName } else { "$vendor $hwModelName".Trim() }
    if ($hwModelNumber -and $hwModelNumber -ne $hwModelName -and -not (Test-JunkSerial $hwModelNumber)) {
        $text += " ($hwModelNumber)"
    }
    $text
}

# Internal disk? USB / virtual never; SD/MMC only as fixed media (soldered eMMC, not a card reader)
function Test-InternalDisk {
    param([string]$BusType, [double]$Size, [bool]$IsFixedMedia)
    $BusType -notin 'USB', 'Virtual', 'File Backed Virtual', 'iSCSI' -and $Size -gt 0 -and
        ($BusType -notin 'SD', 'MMC' -or $IsFixedMedia)
}

# Type label of one disk, e.g. "NVMe SSD", "SATA HDD", "eMMC"; $Name = FriendlyName + Model
function Get-DiskTypeLabel {
    param([string]$BusType, [string]$MediaType, [string]$Name)
    # NVMe behind Intel VMD/RST reports BusType RAID -> fall back to the device name
    # UNTESTED: no VMD/RST laptop available
    $isRaid = $BusType -eq 'RAID'
    if ($BusType -eq 'NVMe') { 'NVMe SSD' }
    elseif ($isRaid -and $Name -match 'NVMe') { 'NVMe SSD' }
    elseif ($isRaid -and $MediaType -eq 'SSD') { 'SSD' }
    elseif ($BusType -in 'SD', 'MMC') { 'eMMC' }
    elseif ($MediaType -in 'SSD', 'HDD') { "$BusType $MediaType" }
    else { $BusType }
}

# One disk: "NVMe SSD"; several: "NVMe SSD 512 GB; SATA HDD 1000 GB" ($Disks: objects with Type, Gb)
function Format-StorageType {
    param([object[]]$Disks)
    if ($Disks.Count -eq 1) { $Disks[0].Type }
    else { ($Disks | ForEach-Object { '{0} {1} GB' -f $_.Type, $_.Gb }) -join '; ' }
}

function New-TagWallpaper {
    param([string]$Tag, [string]$SubText, [string]$BasePath, [string]$OutPath)
    Add-Type -AssemblyName System.Drawing

    # Physical resolution (WinForms Screen bounds are DPI-scaled in PS 5.1)
    $vc = Get-CimInstance Win32_VideoController |
        Where-Object { $_.CurrentHorizontalResolution -gt 0 } | Select-Object -First 1
    $w = 1920; $h = 1080
    if ($vc) { $w = [int]$vc.CurrentHorizontalResolution; $h = [int]$vc.CurrentVerticalResolution }

    $bmp = New-Object Drawing.Bitmap $w, $h
    $g   = [Drawing.Graphics]::FromImage($bmp)
    try {
        $g.SmoothingMode     = 'AntiAlias'
        $g.InterpolationMode = 'HighQualityBicubic'
        $g.TextRenderingHint = 'AntiAliasGridFit'

        if ($BasePath -and (Test-Path $BasePath)) {
            $src = [Drawing.Image]::FromFile($BasePath)
            try {
                # Scale to fill, crop centred
                $scale = [math]::Max($w / $src.Width, $h / $src.Height)
                $dw = $src.Width * $scale; $dh = $src.Height * $scale
                $g.DrawImage($src, [single](($w - $dw) / 2), [single](($h - $dh) / 2), [single]$dw, [single]$dh)
            } finally { $src.Dispose() }
        } else {
            $g.Clear([Drawing.Color]::FromArgb(24, 32, 48))
        }

        $px      = [Drawing.GraphicsUnit]::Pixel
        $tagFont = New-Object Drawing.Font 'Segoe UI', ([single]($h / 20)), ([Drawing.FontStyle]::Bold), $px
        $subFont = New-Object Drawing.Font 'Segoe UI', ([single]($h / 60)), ([Drawing.FontStyle]::Regular), $px
        $boxBrush = New-Object Drawing.SolidBrush ([Drawing.Color]::FromArgb(170, 0, 0, 0))
        try {
            $tagSize = $g.MeasureString($Tag, $tagFont)
            $subSize = $g.MeasureString($SubText, $subFont)
            $pad  = $h / 60
            $boxW = [math]::Max($tagSize.Width, $subSize.Width) + 2 * $pad
            $boxH = $tagSize.Height + $subSize.Height + 2 * $pad
            # Bottom-right, kept clear of the taskbar
            $x = $w - $boxW - $h / 30
            $y = $h - $boxH - $h / 12
            $g.FillRectangle($boxBrush, [single]$x, [single]$y, [single]$boxW, [single]$boxH)
            $g.DrawString($Tag, $tagFont, [Drawing.Brushes]::White, [single]($x + $pad), [single]($y + $pad))
            $g.DrawString($SubText, $subFont, [Drawing.Brushes]::Gainsboro,
                [single]($x + $pad), [single]($y + $pad + $tagSize.Height))
        } finally { $tagFont.Dispose(); $subFont.Dispose(); $boxBrush.Dispose() }

        $dir = Split-Path $OutPath
        if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir | Out-Null }
        $bmp.Save($OutPath, [Drawing.Imaging.ImageFormat]::Png)
    } finally { $g.Dispose(); $bmp.Dispose() }
}

function Set-TagWallpaper {
    param([string]$Path)
    $id      = [Security.Principal.WindowsIdentity]::GetCurrent()
    $isAdmin = (New-Object Security.Principal.WindowsPrincipal $id).IsInRole(
                   [Security.Principal.WindowsBuiltInRole]::Administrator)
    $applied = @()

    if ($isAdmin) {
        # Device-wide: applies to every profile incl. future Entra ID users; also locks the wallpaper.
        # UNVERIFIED on Windows Pro edition.
        $k = 'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\PersonalizationCSP'
        if (-not (Test-Path $k)) { New-Item -Path $k | Out-Null }   # not -Force: it would wipe existing values
        New-ItemProperty -Path $k -Name DesktopImagePath   -Value $Path -PropertyType String -Force | Out-Null
        New-ItemProperty -Path $k -Name DesktopImageUrl    -Value $Path -PropertyType String -Force | Out-Null
        New-ItemProperty -Path $k -Name DesktopImageStatus -Value 1     -PropertyType DWord  -Force | Out-Null
        $applied += 'device'
    }

    if (-not $id.IsSystem) {
        # Current user, immediate effect
        if (-not ('SnipeWallpaper' -as [type])) {
            Add-Type -TypeDefinition @'
using System.Runtime.InteropServices;
public static class SnipeWallpaper {
    [DllImport("user32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
    public static extern bool SystemParametersInfo(int uAction, int uParam, string lpvParam, int fuWinIni);
}
'@
        }
        Set-ItemProperty 'HKCU:\Control Panel\Desktop' -Name WallpaperStyle -Value '10'   # Fill
        Set-ItemProperty 'HKCU:\Control Panel\Desktop' -Name TileWallpaper  -Value '0'
        # SPI_SETDESKWALLPAPER = 20; SPIF_UPDATEINIFILE | SPIF_SENDWININICHANGE = 3
        if ([SnipeWallpaper]::SystemParametersInfo(20, 0, $Path, 3)) { $applied += 'user' }
    }
    $applied -join ','
}

# Returns a status string for the JSON output; never throws
function Update-Wallpaper {
    param([string]$Tag, [string]$SubText)
    if ($NoWallpaper) { return 'skipped' }
    try {
        if ($DryRun) {
            $preview = Join-Path $env:TEMP 'snipeit-wallpaper-preview.png'
            New-TagWallpaper -Tag $Tag -SubText $SubText -BasePath $WallpaperBase -OutPath $preview
            return "preview: $preview"
        }
        New-TagWallpaper -Tag $Tag -SubText $SubText -BasePath $WallpaperBase -OutPath $WallpaperPath
        $scope = Set-TagWallpaper -Path $WallpaperPath
        if ($scope) { "applied: $scope" } else { 'error: not applied' }
    } catch {
        "error: $($_.Exception.Message)"
    }
}

try {
    # A fake serial must never reach Snipe-IT
    if ($Serial -and -not $DryRun) {
        Out-Result @{ result = 'error'; message = '-Serial is only allowed together with -DryRun' } 1
    }

    # Token lookup: -ApiToken > env:SNIPEIT_TOKEN > snipeit.token next to the script (git-ignored).
    # Inside try: an unreadable or empty token file must still produce the JSON line.
    if (-not $ApiToken) {
        $tokenFile = Join-Path $PSScriptRoot 'snipeit.token'
        if (Test-Path $tokenFile) { $ApiToken = "$(Get-Content $tokenFile -Raw)".Trim() }
    }
    if (-not $ApiToken) {
        Out-Result @{ result = 'error'; message = 'API token missing (-ApiToken, env:SNIPEIT_TOKEN or snipeit.token)' } 1
    }

    # Used by Invoke-Snipe
    $base    = $SnipeUrl.TrimEnd('/') + '/api/v1'
    $headers = @{ Authorization = "Bearer $ApiToken"; Accept = 'application/json' }

    # ---------- 1. Hardware inventory ----------
    $bios = Get-CimInstance Win32_BIOS
    $cs   = Get-CimInstance Win32_ComputerSystem
    $csp  = Get-CimInstance Win32_ComputerSystemProduct

    # NB: $hwSerial, not $serial - PS variables are case-insensitive, $serial IS the -Serial parameter
    $hwSerial = if ($Serial) { $Serial.Trim() } else { "$($bios.SerialNumber)".Trim() }
    if (Test-JunkSerial $hwSerial) {
        Out-Result @{ result = 'error'; message = "Invalid BIOS serial: '$hwSerial'" } 1
    }

    $laptopModel = Get-LaptopModelString -Manufacturer $cs.Manufacturer -Model $cs.Model `
        -Version $csp.Version -Sku $cs.SystemSKUNumber

    $cpu = ((Get-CimInstance Win32_Processor | Select-Object -First 1).Name -replace '\s+', ' ').Trim()

    $ramGb = [math]::Round(((Get-CimInstance Win32_PhysicalMemory |
                Measure-Object -Property Capacity -Sum).Sum / 1GB))

    # Internal disks only; size in decimal GB (matches vendor spec, e.g. 512)
    # SD/MMC bus: keep soldered eMMC (fixed media), drop card readers (removable media).
    # Win32_DiskDrive.Index = PhysicalDisk.DeviceId
    # UNTESTED: no eMMC laptop available
    $fixedDiskIds = @(Get-CimInstance Win32_DiskDrive |
        Where-Object { $_.MediaType -eq 'Fixed hard disk media' } | ForEach-Object { "$($_.Index)" })
    $disks = @(Get-PhysicalDisk |
        Where-Object {
            Test-InternalDisk -BusType "$($_.BusType)" -Size $_.Size -IsFixedMedia ("$($_.DeviceId)" -in $fixedDiskIds)
        } |
        Sort-Object { [int]$_.DeviceId } |
        ForEach-Object {
            [pscustomobject]@{
                Type = Get-DiskTypeLabel -BusType "$($_.BusType)" -MediaType "$($_.MediaType)" `
                           -Name "$($_.FriendlyName) $($_.Model)"
                Gb   = [math]::Round($_.Size / 1e9)
            }
        })
    $storageGb   = ($disks | Measure-Object -Property Gb -Sum).Sum
    $storageType = Format-StorageType -Disks $disks

    $os = Get-CimInstance Win32_OperatingSystem
    $osVersion = (Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion' -ErrorAction SilentlyContinue).DisplayVersion
    $osName = ("$($os.Caption) $osVersion" -replace '^Microsoft\s+', '').Trim()   # e.g. "Windows 11 Pro 24H2"

    # Battery health = full charge / design capacity. Optional (desktops, unsupported firmware).
    # 1) root\wmi - BatteryStaticData is missing on many models (e.g. HP), so
    # 2) fall back to powercfg battery report (XML).
    $full = 0; $design = 0
    try {
        $full   = (Get-CimInstance -Namespace root\wmi -ClassName BatteryFullChargedCapacity -ErrorAction Stop |
                    Measure-Object -Property FullChargedCapacity -Sum).Sum
        $design = (Get-CimInstance -Namespace root\wmi -ClassName BatteryStaticData -ErrorAction Stop |
                    Measure-Object -Property DesignedCapacity -Sum).Sum
    } catch { }
    if (-not ($full -gt 0 -and $design -gt 0)) {
        $reportXml = Join-Path $env:TEMP ("battery-{0}.xml" -f [guid]::NewGuid())
        try {
            & powercfg.exe /batteryreport /xml /output $reportXml | Out-Null
            if (Test-Path $reportXml) {
                # Dot-notation ignores the XML namespace
                $bats   = @(([xml](Get-Content $reportXml -Raw)).BatteryReport.Batteries.Battery)
                $full   = ($bats | ForEach-Object { [double]$_.FullChargeCapacity } | Measure-Object -Sum).Sum
                $design = ($bats | ForEach-Object { [double]$_.DesignCapacity }     | Measure-Object -Sum).Sum
            }
        } catch { }
        finally { Remove-Item $reportXml -ErrorAction SilentlyContinue }
    }
    $battery = $null
    if ($full -gt 0 -and $design -gt 0) { $battery = '{0}%' -f [math]::Round($full / $design * 100) }

    $hostname = $env:COMPUTERNAME

    $inventory = [ordered]@{
        hostname     = $hostname
        serial       = $hwSerial
        laptop_model = $laptopModel
        cpu          = $cpu
        ram          = "$ramGb GB"
        storage_gb   = $storageGb
        storage_type = $storageType
        os           = $osName
        battery      = $battery
    }

    $missing = @(@('cpu', 'storage_type', 'os') | Where-Object { -not $inventory[$_] })
    if ($ramGb -le 0)     { $missing += 'ram' }
    if ($storageGb -le 0) { $missing += 'storage_gb' }
    if ($missing) {
        Out-Result (@{ result = 'error'; message = "Required values not collected: $($missing -join ', ')" } + $inventory) 1
    }

    # ---------- 2. Duplicate check ----------
    # Not found = HTTP 200 {"status":"error","messages":"Asset does not exist.","payload":null}
    # (AssetsController::showBySerial). The message is translated to the API user's locale,
    # so match the shape, not the text. Any other error must not be read as "not found".
    # UNTESTED: shape taken from Snipe-IT source, not verified against the live instance
    $existing = Invoke-Snipe GET "/hardware/byserial/$([uri]::EscapeDataString($hwSerial))" -AllowError
    if ($existing.status -eq 'error') {
        if ($null -ne $existing.payload -or $existing.messages -isnot [string]) {
            throw "Snipe-IT API error (GET /hardware/byserial): $($existing.messages | ConvertTo-Json -Compress)"
        }
        $existing = $null
    }
    if ($existing.total -gt 0) {
        $a = $existing.rows | Select-Object -First 1
        $existingTag = [Net.WebUtility]::HtmlDecode($a.asset_tag)   # API returns HTML-encoded strings
        Out-Result @{
            result    = 'exists'
            message   = 'Asset with this serial already registered'
            asset_tag = $existingTag
            id        = $a.id
            serial    = $hwSerial
            matches   = $existing.total
            wallpaper = Update-Wallpaper -Tag $existingTag -SubText "$hostname  |  S/N $hwSerial"
        } 2
    }

    # ---------- 3. Model (read-only, never created) ----------
    if ($ModelId -le 0) {
        $model = Find-ByName 'models' $ModelName
        if (-not $model) {
            Out-Result @{ result = 'error'; message = "Model '$ModelName' not found in Snipe-IT" } 1
        }
        $ModelId = $model.id
    }

    # ---------- 3b. Status label (read-only, never created) ----------
    if ($StatusId -le 0) {
        $statusLabel = Find-ByName 'statuslabels' $StatusName
        if (-not $statusLabel) {
            Out-Result @{ result = 'error'; message = "Status label '$StatusName' not found in Snipe-IT" } 1
        }
        $StatusId = $statusLabel.id
    }

    # ---------- 3c. Custom fields must be in the model's fieldset ----------
    # Snipe-IT silently drops values of fields missing from the fieldset -> fail before creating.
    # default_fieldset_values lists the fieldset's fields (Snipe-IT 6.0.x+, needs only Models view).
    # UNTESTED: response shape taken from Snipe-IT source, not verified against the live instance
    if (-not $model) { $model = Invoke-Snipe GET "/models/$ModelId" }
    if (-not $model.PSObject.Properties['default_fieldset_values']) {
        throw "Model id $ModelId response has no default_fieldset_values (Snipe-IT older than 6.0?)"
    }
    $fieldsetColumns = @($model.default_fieldset_values |
        ForEach-Object { [Net.WebUtility]::HtmlDecode($_.db_column_name) })
    $missingFields = @(@($FieldLaptopModel, $FieldCpu, $FieldRam, $FieldStorageGb, $FieldStorageType,
            $FieldOs, $FieldBattery) | Where-Object { $_ -notin $fieldsetColumns })
    if ($missingFields) {
        Out-Result @{
            result  = 'error'
            message = "Fieldset of model id $ModelId lacks custom fields: $($missingFields -join ', ')"
        } 1
    }

    # ---------- 4. Create asset ----------
    $assetBody = @{
        model_id  = $ModelId
        status_id = $StatusId
        serial    = $hwSerial
        name      = $hostname
    }
    $assetBody[$FieldLaptopModel] = $laptopModel
    $assetBody[$FieldCpu]         = $cpu
    $assetBody[$FieldRam]         = "$ramGb GB"
    $assetBody[$FieldStorageGb]   = "$storageGb"
    $assetBody[$FieldStorageType] = $storageType
    $assetBody[$FieldOs]          = $osName
    if ($battery) { $assetBody[$FieldBattery] = $battery }
    $assetBody.notes = 'Registered by Register-SnipeAsset.ps1 v{0} on {1} by {2} from {3}' -f
        $ScriptVersion, (Get-Date).ToString('yyyy-MM-ddTHH:mm:sszzz'), $RunAs, $hostname

    if ($DryRun) {
        Out-Result @{
            result    = 'dryrun'
            model_id  = $ModelId
            body      = $assetBody
            wallpaper = Update-Wallpaper -Tag 'DRYRUN-0000' -SubText "$hostname  |  S/N $hwSerial"
        } 0
    }

    $created = (Invoke-Snipe POST '/hardware' $assetBody).payload

    $wallpaper = Update-Wallpaper -Tag $created.asset_tag -SubText "$hostname  |  S/N $hwSerial"
    Out-Result (@{ result = 'created'; asset_tag = $created.asset_tag; id = $created.id; wallpaper = $wallpaper } + $inventory) 0
}
catch {
    Out-Result @{ result = 'error'; message = $_.Exception.Message } 1
}
